name: Update README Stats
on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia Ã  meia-noite
  workflow_dispatch: # Permite rodar manualmente
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=Math-Soares&theme=dark&show_icons=true
          path: profile/stats.svg
      - name: Generate Languages
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=Math-Soares&theme=dark&layout=compact
          path: profile/langs.svg
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update stats" || exit 0
          git push
